version: '3'

services:
  # database
  db:
    image: mariadb
    ports:
      - '8082:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./server/database:/var/lib/mysql
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
    links:
      - db:db
  # wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8080:80'
    volumes: 
      - ./server/public:/var/www/html
      - ./server/wp-content/themes:/var/www/html/wp-content/themes
      - ./server/wp-content/uploads:/var/www/html/wp-content/uploads
      - ./server/wp-content/plugins:/var/www/html/wp-content/plugins
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_PASSWORD: password
    links:
      - db:mysql